package tech.codegarage.quotes.model.database;

public enum EnumTag {

    CHARACTER("Character"),
    MOTIVATIONAL("Motivational"),
    DEFEAT("Defeat"),
    GIVE("Give"),
    FRIENDSHIP("Friendship"),
    ME("Me"),
    FLOWER("Flower"),
    SPRING("Spring"),
    BLESSED("Blessed"),
    BROKEN("Broken"),
    FREE("Free"),
    WORLD("World"),
    WINTER("Winter"),
    MAN("Man"),
    ETHICS("Ethics"),
    LIFE("Life"),
    HAPPY("Happy"),
    INTEGRITY("Integrity"),
    RULES("Rules"),
    NEED("Need"),
    GIVING("Giving"),
    GENEROSITY("Generosity"),
    IGNORANCE("Ignorance"),
    TODAY("Today"),
    SUN("Sun"),
    SHINE("Shine"),
    WANT("Want"),
    BEAUTIFUL("Beautiful"),
    FATHER("Father"),
    GOAL("Goal"),
    MISSION("Mission"),
    YOU("You"),
    PERSEVERANCE("Perseverance"),
    GIFT("Gift"),
    BIRD("Bird"),
    LIGHT("Light"),
    FOCUS("Focus"),
    QUALITY("Quality"),
    HABIT("Habit"),
    ROOTS("Roots"),
    SWEET("Sweet"),
    THOUGHT("Thought"),
    MIND("Mind"),
    ART("Art"),
    TRAINING("Training"),
    EXCELLENCE("Excellence"),
    JOB("Job"),
    PERFECTION("Perfection"),
    GENIUS("Genius"),
    LOVE("Love"),
    LOVE_IS("Love Is"),
    SOUL("Soul"),
    INEQUALITY("Inequality"),
    TRY("Try"),
    IMPOSSIBLE("Impossible"),
    EYES("Eyes"),
    KINDNESS("Kindness"),
    BE_HAPPY(" Be Happy"),
    PASSION("Passion"),
    DAY("Day"),

    HAIR("Hair"),
    WOMAN ("Woman"),
    TOMORROW("Tomorrow"),
    CAKE("Cake"),
    COFFEE("Coffee"),
    TEA("Tea"),
    TREE("Tree"),
    SHADOW("Shadow"),
    I_AM("I Am"),
    WALK("Walk"),
    SLOW("Slow"),
    STAND("Stand"),
    FEET("Feet"),
    MOTHER("Mother"),
    ADVERSITY("Adversity"),
    AMERICA("America"),
    WILL("Will"),

    AGE("Age"),
    ALONE("Alone"),
    AMAZING("Amazing"),
    ANGER("Anger"),
    ANNIVERSARY("Anniversary"),
    ARCHITECTURE("Architecture"),
    ART_FAVORITE("Art Favorite"),
    ATTITUDE("Attitude"),
    BEAUTY("Beauty"),
    BEST("Best"),
    BIRTHDAY("Birthday"),
    BRAINY("Brainy"),
    BUSINESS("Business"),
    CAR("Car"),
    CHANCE("Chance"),
    CHANGE("Change"),
    CHRISTMAS("Christmas"),
    COMMUNICATION("Communication"),
    COMPUTERS("Computers"),
    COOL("Cool"),
    COURAGE("Courage"),
    DAD("Dad"),
    DATING("Dating"),
    DEATH("Death"),
    DESIGN("Design"),
    DIET("Diet"),
    DREAMS("Dreams"),
    DOORS("Doors"),
    EASTER("Easter"),
    EDUCATION("Education"),
    ENVIRONMENTAL("Environmental"),
    EQUALITY("Equality"),
    EXPERIENCE("Experience"),
    FAILURE("Failure"),
    FAITH("Faith"),
    FAMILY("Family"),
    FAMOUS("Famous"),
    FATHERS_DAY("Father's Day"),
    FEAR("Fear"),
    FINANCE("Finance"),
    FITNESS("Fitness"),
    FOOD("Food"),
    FORGIVENESS("Forgiveness"),
    FREEDOM("Freedom"),
    FRIENDSHIP_FAVORITE("Friendship Favorite"),
    FUNNY("Funny"),
    FUTURE("Future"),
    GARDENING("Gardening"),
    GOD("God"),
    GOOD("Good"),
    GOVERNMENT("Government"),
    GRADUATION("Graduation"),
    GREAT("Great"),
    HAPPINESS("Happiness"),
    HEALTH("Health"),
    HISTORY("History"),
    HOME("Home"),
    HOPE("Hope"),
    HUMOR("Humor"),
    IMAGINATION("Imagination"),
    INDEPENDENCE("Independence"),
    INSPIRATIONAL("Inspirational"),
    INTELLIGENCE("Intelligence"),
    JEALOUSY("Jealousy"),
    KNOWLEDGE("Knowledge"),
    LEADERSHIP("Leadership"),
    LEARNING("Learning"),
    LEGAL("Legal"),
    LIFE_FAV0RITE("Life Favorite"),
    LOVE_FAVORITE("Love Favorite"),
    MARRIAGE("Marriage"),
    MEDICAL("Medical"),
    MEMORIAL_DAY("Memorial Day"),
    MEN("Men"),
    MOM("Mom"),
    MONEY("Money"),
    MORNING("Morning"),
    MOTHERS_DAY("Mother's Day"),
    MOTIVATIONAL_FAVORITE("Motivational Favorite"),
    MOVIES("Movies"),
    MOVING_ON("Moving On"),
    MUSIC("Music"),
    NATURE("Nature"),
    NEW_YEARS("New Year's"),
    PARENTING("Parenting"),
    PATIENCE("Patience"),
    PATRIOTISM("Patriotism"),
    PEACE("Peace"),
    PET("Pet"),
    POETRY("Poetry"),
    POLITICS("Politics"),
    POSITIVE("Positive"),
    POWER("Power"),
    PERCEPTION("Perception"),
    RELATIONSHIP("Relationship"),
    RELIGION("Religion"),
    RESPECT("Respect"),
    ROMANTIC("Romantic"),
    SAD("Sad"),
    SAINT_PATRICKS_DAY("Saint Patrick's Day"),
    SCIENCE("Science"),
    SMILE("Smile"),
    SOCIETY("Society"),
    SPACE("Space"),
    SPORTS("Sports"),
    STRENGTH("Strength"),
    SUCCESS_FAVORITE("Success Favorite"),
    SELF("Self"),
    SYMPATHY("Sympathy"),
    TEACHER("Teacher"),
    TECHNOLOGY("Technology"),
    TEEN("Teen"),
    THANKFUL("Thankful"),
    THANKSGIVING("Thanksgiving"),
    TIME("Time"),
    TRAVEL("Travel"),
    TRUST("Trust"),
    TRUTH("Truth"),
    UNIVERSE("Universe"),
    VALENTINES_DAY("Valentine's Day"),
    VETERANS_DAY("Veterans Day"),
    WAR("War"),
    WEDDING("Wedding"),
    WISDOM("Wisdom Favorite"),
    WOMEN("Women"),
    WORK("Work"),

    MSDSDSSDSADSDSADSDSZDSZDSZDSDXFCDSFCFDDSZDE("Medfdfdxfdfdxfvdsfvdfdsfdxfdxfdxfvdxfvdxfdxf");


    private LitePalTag litePalTag;

    EnumTag(String tagName) {
        litePalTag = LitePalDataHandler.insetTag(new LitePalTag(tagName));
    }

    public LitePalTag getLitePalTag() {
        return litePalTag;
    }
}
