package tech.codegarage.quotes.model.database;

public enum EnumTag {

    CHARACTER("Character"),
    MOTIVATIONAL("Motivational"),
    DEFEAT("Defeat"),
    GIVE("Give"),
    FRIENDSHIP("Friendship"),
    ME("Me"),
    FLOWER("Flower"),
    SPRING("Spring"),
    BLESSED("Blessed"),
    BROKEN("Broken"),
    FREE("Free"),
    WORLD("World"),
    WINTER("Winter"),
    MAN("Man"),
    ETHICS("Ethics"),
    LIFE("Life"),
    HAPPY("Happy"),
    INTEGRITY("Integrity"),
    RULES("Rules"),
    NEED("Need"),
    GIVING("Giving"),
    GENEROSITY("Generosity"),
    IGNORANCE("Ignorance"),
    TODAY("Today"),
    SUN("Sun"),
    SHINE("Shine"),
    WANT("Want"),
    BEAUTIFUL("Beautiful"),
    FATHER("Father"),
    GOAL("Goal"),
    MISSION("Mission"),
    YOU("You"),
    PERSEVERANCE("Perseverance"),
    GIFT("Gift"),
    BIRD("Bird"),
    LIGHT("Light"),
    FOCUS("Focus"),
    QUALITY("Quality"),
    HABIT("Habit"),
    ROOTS("Roots"),
    SWEET("Sweet"),
    THOUGHT("Thought"),
    TRAINING("Training"),
    EXCELLENCE("Excellence"),
    JOB("Job"),
    PERFECTION("Perfection"),
    GENIUS("Genius"),
    LOVE_IS("Love Is"),
    INEQUALITY("Inequality"),
    TRY("Try"),
    IMPOSSIBLE("Impossible"),
    KINDNESS("Kindness"),
    BE_HAPPY(" Be Happy"),
    PASSION("Passion"),
    DAY("Day"),
    HAIR("Hair"),
    TOMORROW("Tomorrow"),
    CAKE("Cake"),
    COFFEE("Coffee"),
    TEA("Tea"),
    TREE("Tree"),
    SHADOW("Shadow"),
    I_AM("I Am"),
    WALK("Walk"),
    SLOW("Slow"),
    STAND("Stand"),
    FEET("Feet"),
    MOTHER("Mother"),
    ADVERSITY("Adversity"),
    AMERICA("America"),
    WILL("Will"),
    AGE("Age"),
    ALONE("Alone"),
    AMAZING("Amazing"),
    ANNIVERSARY("Anniversary"),
    ARCHITECTURE("Architecture"),
    ART_FAVORITE("Art Favorite"),
    ATTITUDE("Attitude"),
    BEAUTY("Beauty"),
    BECAUSE("Because"),
    BEST("Best"),
    BIRTHDAY("Birthday"),
    BRAINY("Brainy"),
    BUSINESS("Business"),
    CAR("Car"),
    CHANCE("Chance"),
    CHANGE("Change"),
    CHRISTMAS("Christmas"),
    COMMUNICATION("Communication"),
    COMPUTERS("Computers"),
    COOL("Cool"),
    COURAGE("Courage"),
    COUNTRY("Country"),
    CHILD("Child"),
    DAD("Dad"),
    DATING("Dating"),
    DEATH("Death"),
    DESIGN("Design"),
    DEMOCRACY("Democracy"),
    DIET("Diet"),
    DREAMS("Dreams"),
    DOORS("Doors"),
    DISCOVER("Discover"),
    DESIRE("Desire"),
    EASTER("Easter"),
    EDUCATION("Education"),
    ENVIRONMENTAL("Environmental"),
    EQUALITY("Equality"),
    EXPERIENCE("Experience"),
    EXPRESSING("Expressing"),
    EXIST("Exist"),
    FAILURE("Failure"),
    FAITH("Faith"),
    FAMILY("Family"),
    FAMOUS("Famous"),
    FATHERS_DAY("Father's Day"),
    FACTS("Facts"),
    FEAR("Fear"),
    FINANCE("Finance"),
    FIRST("First"),
    FOOD("Food"),
    FREEDOM("Freedom"),
    FRIENDSHIP_FAVORITE("Friendship Favorite"),
    GARDENING("Gardening"),
    GOD("God"),
    GOOD("Good"),
    GOVERNMENT("Government"),
    GRADUATION("Graduation"),
    GREAT("Great"),
    HAPPINESS("Happiness"),
    HEALTH("Health"),
    HISTORY("History"),
    HOME("Home"),
    HOPE("Hope"),
    HUMOR("Humor"),
    IMAGINATION("Imagination"),
    INDEPENDENCE("Independence"),
    INSPIRATIONAL("Inspirational"),
    INTELLIGENCE("Intelligence"),
    JEALOUSY("Jealousy"),
    JUSTICE("Justice"),
    KNOWLEDGE("Knowledge"),
    LEADERSHIP("Leadership"),
    LEARNING("Learning"),
    LEARN("Learn"),
    LEGAL("Legal"),
    LIBERTY("Liberty"),
    LIFE_FAV0RITE("Life Favorite"),
    LOVE_FAVORITE("Love Favorite"),
    MARRIAGE("Marriage"),
    MEDICAL("Medical"),
    MEMORIAL_DAY("Memorial Day"),
    MEN("Men"),
    MISTAKE("Mistake"),
    MOM("Mom"),
    MONEY("Money"),
    MORNING("Morning"),
    MOTHERS_DAY("Mother's Day"),
    MOTIVATIONAL_FAVORITE("Motivational Favorite"),
    MOVIES("Movies"),
    MOVING_ON("Moving On"),
    MUSIC("Music"),
    NEW_YEARS("New Year's"),
    NEVER("Never"),
    NERVOUS("Nervous"),
    PARENTING("Parenting"),
    PATIENCE("Patience"),
    PATRIOTISM("Patriotism"),
    PEACE("Peace"),
    PET("Pet"),
    PERFECT("Perfect"),
    POETRY("Poetry"),
    POWERFUL("Powerful"),
    POLITICS("Politics"),
    POSITIVE("Positive"),
    POWER("Power"),
    PROMISE("Promise"),
    PERCEPTION("Perception"),
    RELATIONSHIP("Relationship"),
    REAL("Real"),
    RISE("Rise"),
    RELIGION("Religion"),
    RESPECT("Respect"),
    ROMANTIC("Romantic"),
    SAD("Sad"),
    SAME("Same"),
    SAINT_PATRICKS_DAY("Saint Patrick's Day"),
    SCIENCE("Science"),
    SMILE("Smile"),
    SOCIETY("Society"),
    SPACE("Space"),
    SPORTS("Sports"),
    STRONG("Strong"),
    SUCCESS_FAVORITE("Success Favorite"),
    SELF("Self"),
    SYMPATHY("Sympathy"),
    SILENCE("Silence"),
    TEACHER("Teacher"),
    TECHNOLOGY("Technology"),
    TEEN("Teen"),
    THANKFUL("Thankful"),
    THANKSGIVING("Thanksgiving"),
    THINK("Think"),
    TIME("Time"),
    TRAVEL("Travel"),
    TYRANNY("Tyranny"),
    TRUST("Trust"),
    TRUTH("Truth"),
    UNIVERSE("Universe"),
    VALENTINES_DAY("Valentine's Day"),
    VETERANS_DAY("Veterans Day"),
    WAR("War"),
    WEDDING("Wedding"),
    WISDOM("Wisdom Favorite"),
    WOMEN("Women"),
    WORK("Work"),
    WRONG("Wrong"),
    EYES("Eyes"),
    LOOK("Look"),
    OWN("OWN"),
    ANGELS("Angels"),
    TREAD("Tread"),
    WHERE("Where"),
    NATURE("Nature"),
    ART("Art"),
    THEE("Thee"),
    ASHAMED("Ashamed"),
    WHICH("Which"),
    LOVE("Love"),
    WOMAN("Woman"),
    EVER("Ever"),
    TEACH("Teach"),
    SHOW("Show"),
    ANOTHER("Another"),
    SOUL("Soul"),
    STRIKE("Strike"),
    WINS("Wins"),
    OCEAN("Ocean"),
    REASONS("Reasons"),
    GALE("Gale"),
    ANGER("Anger"),
    REVENGE("Revenge"),
    ANGRY("Angry"),
    FORGIVENESS("Forgiveness"),
    FORGIVE("Forgive"),
    ERR("Err"),
    EVERYBODY("Everybody"),
    WORST_THING("Worst Thing"),
    FUNNY("Funny"),
    SIMPLE("Simple"),
    FAT("Fat"),
    FITNESS("Fitness"),
    LIKE("Like"),
    OTHER("Other"),
    BRING("Bring"),
    IMPROVES("Improves"),
    MIND("Mind"),
    YOU_CAN_DO_IT("You Can Do It"),
    FACT("Fact"),
    FUTURE("Future"),
    GREEN("Green"),
    RENEWABLE("Renewable"),
    GROW("Grow"),
    GROW_UP("Grow Up"),
    MILK("Milk"),
    CONQUER("Conquer"),
    SURVIVE("Survive"),
    MOVE("Move"),
    REMEMBER("Remember"),
    CLIMB("Climb"),
    LADDER("Ladder"),
    STRENGTH("Strength"),
    HARDSHIPS("Hardships"),
    THROUGH("Through"),

    MSDSDSSDSADSDSADSDSZDSZDSZDSDXFCDSFCFDDSZDE("Medfdfdxfdfdxfvdsfvdfdsfdxfdxfdxfvdxfvdxfdxf");


    private LitePalTag litePalTag;

    EnumTag(String tagName) {
        litePalTag = LitePalDataHandler.insetTag(new LitePalTag(tagName), LitePalDataHandler.dataInputListener);
    }

    public LitePalTag getLitePalTag() {
        return litePalTag;
    }
}
