package tech.codegarage.quotes.model.database;

public enum EnumTag {

    CHARACTER("Character"),
    DEFEAT("Defeat"),
    FRIENDSHIP("Friendship"),
    ME("Me"),
    FLOWER("Flower"),
    SPRING("Spring"),
    BLESSED("Blessed"),
    BROKEN("Broken"),
    FREE("Free"),
    WINTER("Winter"),
    MAN("Man"),
    ETHICS("Ethics"),
    INTEGRITY("Integrity"),
    RULES("Rules"),
    NEED("Need"),
    GIVING("Giving"),
    GENEROSITY("Generosity"),
    IGNORANCE("Ignorance"),
    TODAY("Today"),
    SUN("Sun"),
    SHINE("Shine"),
    WANT("Want"),
    BEAUTIFUL("Beautiful"),
    FATHER("Father"),
    GOAL("Goal"),
    MISSION("Mission"),
    YOU("You"),
    PERSEVERANCE("Perseverance"),
    GIFT("Gift"),
    BIRD("Bird"),
    LIGHT("Light"),
    FOCUS("Focus"),
    QUALITY("Quality"),
    HABIT("Habit"),
    ROOTS("Roots"),
    SWEET("Sweet"),
    TRAINING("Training"),
    EXCELLENCE("Excellence"),
    JOB("Job"),
    PERFECTION("Perfection"),
    GENIUS("Genius"),
    LOVE_IS("Love Is"),
    INEQUALITY("Inequality"),
    TRY("Try"),
    IMPOSSIBLE("Impossible"),
    KINDNESS("Kindness"),
    BE_HAPPY(" Be Happy"),
    PASSION("Passion"),
    DAY("Day"),

    HAIR("Hair"),
    TOMORROW("Tomorrow"),
    CAKE("Cake"),
    COFFEE("Coffee"),
    TEA("Tea"),
    TREE("Tree"),
    SHADOW("Shadow"),
    WALK("Walk"),
    SLOW("Slow"),
    STAND("Stand"),
    FEET("Feet"),
    MOTHER("Mother"),
    ADVERSITY("Adversity"),
    AMERICA("America"),

    AGE("Age"),
    ALONE("Alone"),
    AMAZING("Amazing"),
    ANNIVERSARY("Anniversary"),
    ARCHITECTURE("Architecture"),
    ART_FAVORITE("Art Favorite"),
    ATTITUDE("Attitude"),
    BEAUTY("Beauty"),
    BECAUSE("Because"),
    BIRTHDAY("Birthday"),
    BRAINY("Brainy"),
    BUSINESS("Business"),
    CAR("Car"),
    CHANCE("Chance"),
    CHRISTMAS("Christmas"),
    COMMUNICATION("Communication"),
    COMPUTERS("Computers"),
    COOL("Cool"),
    CHILD("Child"),
    DAD("Dad"),
    DATING("Dating"),
    DEATH("Death"),
    DESIGN("Design"),
    DEMOCRACY("Democracy"),
    DIET("Diet"),
    DREAMS("Dreams"),
    DOORS("Doors"),
    DISCOVER("Discover"),
    DESIRE("Desire"),
    EASTER("Easter"),
    ENVIRONMENTAL("Environmental"),
    EQUALITY("Equality"),
    EXPERIENCE("Experience"),
    EXPRESSING("Expressing"),
    EXIST("Exist"),
    FAITH("Faith"),
    FAMOUS("Famous"),
    FATHERS_DAY("Father's Day"),
    FACTS("Facts"),
    FEAR("Fear"),
    FINANCE("Finance"),
    FIRST("First"),
    FOOD("Food"),
    FRIENDSHIP_FAVORITE("Friendship Favorite"),
    GARDENING("Gardening"),
    GOD("God"),
    GOOD("Good"),
    GOVERNMENT("Government"),
    GRADUATION("Graduation"),
    GREAT("Great"),
    HAPPINESS("Happiness"),
    HISTORY("History"),
    HOME("Home"),
    HOPE("Hope"),
    HUMOR("Humor"),
    IMAGINATION("Imagination"),
    INDEPENDENCE("Independence"),
    INTELLIGENCE("Intelligence"),
    JEALOUSY("Jealousy"),
    JUSTICE("Justice"),
    LEADERSHIP("Leadership"),
    LEARN("Learn"),
    LEGAL("Legal"),
    LIBERTY("Liberty"),
    LIFE_FAV0RITE("Life Favorite"),
    LOVE_FAVORITE("Love Favorite"),
    MARRIAGE("Marriage"),
    MEDICAL("Medical"),
    MEMORIAL_DAY("Memorial Day"),
    MEN("Men"),
    MISTAKE("Mistake"),
    MOM("Mom"),
    MORNING("Morning"),
    MOTHERS_DAY("Mother's Day"),
    MOTIVATIONAL_FAVORITE("Motivational Favorite"),
    MOVIES("Movies"),
    MOVING_ON("Moving On"),
    MUSIC("Music"),
    NEW_YEARS("New Year's"),
    PARENTING("Parenting"),
    PATIENCE("Patience"),
    PATRIOTISM("Patriotism"),
    PEACE("Peace"),
    PET("Pet"),
    POETRY("Poetry"),
    POWERFUL("Powerful"),
    POSITIVE("Positive"),
    PROMISE("Promise"),
    PERCEPTION("Perception"),
    RELATIONSHIP("Relationship"),
    REAL("Real"),
    RISE("Rise"),
    RELIGION("Religion"),
    RESPECT("Respect"),
    ROMANTIC("Romantic"),
    SAD("Sad"),
    SAME("Same"),
    SAINT_PATRICKS_DAY("Saint Patrick's Day"),

    SMILE("Smile"),
    SOCIETY("Society"),
    SPACE("Space"),
    SPORTS("Sports"),
    SUCCESS_FAVORITE("Success Favorite"),
    SELF("Self"),
    SYMPATHY("Sympathy"),
    SILENCE("Silence"),
    TEACHER("Teacher"),
    TEEN("Teen"),
    THANKFUL("Thankful"),
    THANKSGIVING("Thanksgiving"),
    TIME("Time"),
    TRAVEL("Travel"),
    TYRANNY("Tyranny"),
    TRUST("Trust"),
    UNIVERSE("Universe"),
    VALENTINES_DAY("Valentine's Day"),
    VETERANS_DAY("Veterans Day"),
    WEDDING("Wedding"),
    WISDOM("Wisdom Favorite"),
    WOMEN("Women"),
    WORK("Work"),
    WRONG("Wrong"),

    EYES("Eyes"),
    LOOK("Look"),
    OWN("OWN"),
    ANGELS("Angels"),
    TREAD("Tread"),
    WHERE("Where"),
    NATURE("Nature"),
    ART("Art"),
    THEE("Thee"),
    ASHAMED("Ashamed"),
    WOMAN("Woman"),
    EVER("Ever"),
    TEACH("Teach"),
    SHOW("Show"),
    ANOTHER("Another"),
    SOUL("Soul"),
    STRIKE("Strike"),
    WINS("Wins"),
    OCEAN("Ocean"),
    REASONS("Reasons"),
    GALE("Gale"),
    ANGER("Anger"),
    REVENGE("Revenge"),
    ANGRY("Angry"),
    FORGIVENESS("Forgiveness"),
    FORGIVE("Forgive"),
    ERR("Err"),
    WORST_THING("Worst Thing"),
    SIMPLE("Simple"),
    FAT("Fat"),
    FITNESS("Fitness"),
    LIKE("Like"),
    BRING("Bring"),
    IMPROVES("Improves"),
    MIND("Mind"),
    YOU_CAN_DO_IT("You Can Do It"),
    FUTURE("Future"),
    GREEN("Green"),
    RENEWABLE("Renewable"),
    GROW_UP("Grow Up"),
    MILK("Milk"),
    CONQUER("Conquer"),
    SURVIVE("Survive"),
    MOVE("Move"),
    CLIMB("Climb"),
    LADDER("Ladder"),
    STRENGTH("Strength"),
    HARDSHIPS("Hardships"),
    THROUGH("Through"),
    CHANGE("Change"),
    WAIT("Wait"),
    COUNTRY("Country"),
    BIG("Big"),
    STRONG("Strong"),
    POLITICS("Politics"),
    POLITICAL("Political"),
    VALUES("Values"),
    PATH("Path"),
    RIGHT_PATH("Right Path"),
    MYSELF("Myself"),
    ANSWER("Answer"),
    MONEY("Money"),
    LEADER("Leader"),
    CONGRESS("Congress"),
    WORKS("Works"),
    LAW("Law"),
    STRIVING("Striving"),
    HISTORIC("Historic"),
    WALKING("Walking"),
    THEM("Them"),

    ALLIGATOR("Alligator"),
    HAPPY("Happy"),
    INCOME("Income"),
    LEAST("Least"),
    REALISM("Realism"),
    DISTRUST("Distrust"),
    CYNICISM("Cynicism"),
    FAMILY("Family"),
    UNITED("United"),
    MATT("Matt"),
    SEEN("Seen"),
    CONSUME("Consume"),
    UNITS("Units"),
    ALLOW("Allow"),
    MORAL("Moral"),
    RELIGIOUS("Religious"),
    CONCEPT("Concept"),
    BEHIND("Behind"),
    EVENTUALLY("Eventually"),
    DISLIKE("Dislike"),
    FORCED("Forced"),
    STARVE("Starve"),
    DESTROY("Destroy"),
    WHICH("Which"),
    MEMORY("Memory"),
    CITY("City"),
    SOME("Some"),
    POWER("Power"),
    SOCIAL("Social"),
    TRUTH("Truth"),
    FEELING("Feeling"),
    COURAGE("Courage"),
    FIRE("Fire"),
    SMOKE("Smoke"),
    FREEDOM("Freedom"),
    THOUGHT("Thought"),
    PUBLIC("Public"),
    HEALTH("Health"),
    WISE("Wise"),
    BED("Bed"),
    READING("Reading"),
    WRITING("Writing"),
    EITHER("Either"),
    PREPARE("Prepare"),
    FAIL("Fail"),
    FUNNY("Funny"),
    SEE("See"),
    CONSTANT("Constant"),
    KNOWLEDGE("Knowledge"),
    WORK_HARD("Work Hard"),
    MOTIVATIONAL("Motivational"),
    BETTER("Better"),
    THAN("Than"),
    SUCCESS("Success"),
    REMEMBER("Remember"),
    FORGET("Forget"),
    EDUCATION("Education"),
    BEST("Best"),
    INTEREST("Interest"),
    DIE("Die"),
    NEVER("Never"),
    SCIENCE("Science"),
    PHILOSOPHY("Philosophy"),
    KNOW("Know"),
    STUPID("Stupid"),
    MADE("Made"),
    MANKIND("Mankind"),
    WILL("Will"),
    ONLY("Only"),
    INSPIRATIONAL("Inspirational"),
    MAGICAL("Magical"),
    BEGINNING("Beginning"),
    CRUELTY("Cruelty"),
    SOURCES("Sources"),
    FACT("Fact"),
    BEEN("Been"),
    UTTERLY("Utterly"),
    WORLD("World"),
    TROUBLE("Trouble"),
    WAR("War"),
    LEFT("Left"),
    DETERMINE("Determine"),
    LOVE("Love"),
    LIFE("Life"),
    INSPIRED("Inspired"),
    GROW("Grow"),
    PERFECT("Perfect"),
    I_AM("I Am"),
    STAGE("Stage"),
    VERY("Very"),
    AGAINST("Against"),
    SOON("Soon"),
    GOTTEN("Gotten"),
    MEANS("Means"),
    REVEAL("Reveal"),
    ANSWERS("Answers"),
    ABOUT("About"),
    MY_LIFE("My Life"),
    SHUT("Shut"),
    FRUSTRATED("Frustrated"),
    ALWAYS("Always"),
    INDULGENCE("Indulgence"),
    NERVOUS("Nervous"),
    GOING("Going"),
    GET("Get"),
    EVERYBODY("Everybody"),
    SCREAM("Scream"),
    HOLD("Hold"),
    SEXY("Sexy"),
    SIDE("Side"),
    PERFORMER("Performer"),
    TECHNOLOGY("Technology"),
    EFFICIENCY("Efficiency"),
    YOUR_CHILD("Your Child"),
    HALF("Half"),
    FEEDBACK("Feedback"),
    GIVE("Give"),
    HOW("How"),
    LEARNING("Learning"),
    UNHAPPY("Unhappy"),
    MOST("Most"),
    PART("Part"),
    MAKING("Making"),
    BASED("Based"),
    SQUARE("Square"),
    BECOMING("Becoming"),
    TOWN("Town"),
    THINK("Think"),
    OTHER("Other"),
    FAILURE("Failure"),
    IMPORTANT("Important"),
    FINE("Fine"),
    MOTIVATING("Motivating"),
    SMART_PEOPLE("Smart People"),
    SUCCESS_IS("Success Is"),
    CONSTANCY("Constancy"),
    I_REMEMBER("I Remember"),
    REGRET("Regret"),
    MANHOOD("Manhood"),
    OLD("Old"),
    HEROES("Heroes"),
    STUDYING("Studying"),
    SEEING("Seeing"),
    PILLARS("Pillars"),
    EXPLAIN("Explain"),
    ACHIEVEMENT("Achievement"),
    WORDS("Words"),





    BETTER("Better"),
    THAN("Than"),
    MUSIC("Music"),
    I_LOVE("I Love"),
    PRACTICE("Practice"),
    GETS("Gets"),
    WORKING("Working"),
    OVER("Over"),
    FEEL("Feel"),
    SCARE("Scare"),
    PLANET("Planet"),
    HAPPIER("Happier"),
    LASTS("Lasts"),
    BELIEVE("Believe"),
    INDUSTRY("Industry"),
    MIKE("Mike"),
    LOT("Lot"),
    TOOK("Took"),
    HUMBLING("Humbling"),
    WATCH("Watch"),
    HONESTLY("Honestly"),
    GO("Go"),
    PHASE("Phase"),
    PASADENA("Pasadena"),
    MARKETS("Markets"),
    ROLE("Role"),
    COCKY("Cocky"),
    BRILLIANT("Brilliant"),
    VEGETARIAN("Vegetarian"),
    MOSTLY("Mostly"),
    ROME("Rome"),
    HOMELAND("Homeland"),
    HAD("Had"),
    PLAY("Play"),
    CHARACTERS("Characters"),
    DARKER("Darker"),
    MORE("More"),
    BUYS("Buys"),
    YES("Yes"),
    NEW("New"),
    NEEDS("Needs"),
    CELEBRITIES("Celebrities"),
    THREAD("Thread"),
    DAVID_CAMERON("David Cameron"),
    LONDON("London"),
    SPECIAL("Special"),
    PARKS("Parks"),
    BUS("Bus"),
    SIMILAR("Similar"),
    ECONOMIES("Economies"),
    LARGEST("Largest"),
    NEGATIVE("Negative"),
    ALTITUDE("Altitude"),
    WINNER("Winner"),
    EXPECT("Expect"),
    GUILT("Guilt"),
    NOTHING("Nothing"),
    WEEKNESS("Greatness"),
    GREATNESS("Weakness"),
    ENGINEERED("Engineered"),
    WERE("Were"),
    MOTIVATION("Motivation"),
    WHY("Why"),
    LAST("Last"),
    SURELY("Surely"),
    QUICKLY("Quickly"),
    BONDS("Bonds"),
    DOING("Doing"),
    AWFUL("Awful"),
    LOWER("Lower"),
    CONCERNED("Concerned"),
    POSSESSION("Possession"),
    RELATIONSHIPS("Relationships"),
    STILL("Still"),
    SURE("Sure"),
    ASHES("Ashes"),
    PILE("Pile"),
    PASSIONATE("Passionate"),
    I_THINK("I Think"),
    HELP("Help"),
    TASK("Task"),
    INDIVIDUAL("Individual"),
    AVERAGE("Average"),
    MSDSDSSDSADSDSADSDSZDSZDSZDSDXFCDSFCFDDSZDE("Medfdfdxfdfdxfvdsfvdfdsfdxfdxfdxfvdxfvdxfdxf");


    private LitePalTag litePalTag;

    EnumTag(String tagName) {
        litePalTag = LitePalDataHandler.insetTag(new LitePalTag(tagName), LitePalDataHandler.dataInputListener);
    }

    public LitePalTag getLitePalTag() {
        return litePalTag;
    }
}
